general:
steps:
  mtaBuild:
    buildTarget: 'CF'
    
    
    
    
  
cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: '4841fdcetrial'
      space: 'dev'
      credentialsId: 'CF_CREDENTIALSID'
